In [37]:
import numpy as np
import cv2
import time

In [38]:
def calculate_path(atype,mat,V):
    row_q.append(start_pixel_x)
    col_q.append(start_pixel_y)
    pixel_counted[start_pixel_x,start_pixel_y] = True
    global end_reached
    global next_branch_pixels_count
    global current_branch_pixel_count, next_branch_pixels_count, steps_in_path
    while len(row_q) > 0:
        rd = row_q.pop(0)
        cd = col_q.pop(0)
        if [rd,cd] == [end_pixel_x,end_pixel_y]:
            end_reached = True
            break
        if atype == '4':
            dr = [-1,1,0,0] 
            dc = [0,0,1,-1]
            for i in range(4):
              rr = rd + dr[i] 
              cc = cd + dc[i]
              if rr < 0 or cc < 0 or rr >= row or cc >= col or not(A[rr,cc] in V) or pixel_counted[rr,cc] ==True :
                continue
              row_q.append(rr)
              col_q.append(cc)
              pixel_counted[rr,cc] = True
              next_branch_pixels_count = next_branch_pixels_count + 1
        elif atype == '8':
            dr = [-1,1,0,0,-1,+1,-1,1]
            dc = [0,0,1,-1,-1,-1,1,1]
            for i in range(8):
              rr = rd + dr[i]
              cc = cd + dc[i]
              if rr < 0 or cc < 0 or rr >= row or cc >= col or not(A[rr,cc] in V) or pixel_counted [rr,cc]== True:
                continue
              row_q.append(rr)
              col_q.append(cc)
              pixel_counted[rr,cc] = True
              next_branch_pixels_count = next_branch_pixels_count + 1
        elif atype == 'm':
            dr = [-1,1,0,0,-1,+1,-1,1]
            dc = [0,0,1,-1,-1,-1,1,1]
            for i in range(8):
              rr = rd + dr[i]
              cc = cd + dc[i]
              if rr < 0 or cc < 0 or rr >= row or cc >= col or pixel_counted [rr,cc]==True or not(A[rr,cc] in V):
               continue
              if rr == rd - 1 and cc == cd - 1 and ((A[rd-1,cd] in V) or (A[rd,cd-1] in V)):
               continue
              if rr == rd + 1 and cc == cd - 1 and ((A[rd+1,cd] in V) or (A[rd,cd-1] in V)):
               continue
              if rr == rd - 1 and cc == cd + 1 and ((A[rd,cd+1] in V) or (A[rd-1,cd] in V)):
               continue
              if rr == rd + 1 and cc == cd + 1 and ((A[rd,cd+1] in V) or (A[rd+1,cd] in V)):
               continue
              row_q.append(rr)
              col_q.append(cc)
              pixel_counted[rr,cc] = True
        
              next_branch_pixels_count = next_branch_pixels_count + 1
        
        if len(row_q) == 0:
            break       
        current_branch_pixel_count = current_branch_pixel_count - 1
        if current_branch_pixel_count == 0:
            current_branch_pixel_count = next_branch_pixels_count
            next_branch_pixels_count = 0
            steps_in_path = steps_in_path + 1
            pixel_paths.append([rd,cd])   
    if end_reached:
        pixel_paths.append([end_pixel_x,end_pixel_y])
        return steps_in_path, pixel_paths
    else:
        return False
    
    

    
# Example 1
start_time = time.time()
A = np.array(([3,1,2,1],[2,2,0,2],[1,2,1,1],[1,0,1,2]))
row = A.shape[0]
col = A.shape[1]
V2 = [1,2] 
V1 = [0,1]
start_pixel_x = 3
start_pixel_y = 0
end_pixel_x = 0
end_pixel_y = 3

L = ['4','8','m']

for i in L:
  row_q = [] 
  col_q = []
  pixel_counted = np.zeros((row,col)).astype(bool)
  pixel_paths = []
  steps_in_path = 0
  current_branch_pixel_count = 1
  next_branch_pixels_count = 0
  end_reached = False
  if i == '4':
    path4 = calculate_path('4',A,V1)
  elif i == '8':
    path8 = calculate_path('8',A,V1)
  elif i =='m':
    pathm = calculate_path('m',A,V1)
    
    
    
print("Image1-V1 = \n",A)
print("Set =",V1)
print("Path4 = ",path4)
print("Path8 = ",path8)
print("Pathm = ",pathm)
print('\n')



# Example 2
A = np.array(([3,1,2,1],[2,2,0,2],[1,2,1,1],[1,0,1,2]))
row = A.shape[0]
col = A.shape[1]
V2 = [1,2] 
V1 = [0,1]
start_pixel_x = 3
start_pixel_y = 0
end_pixel_x = 0
end_pixel_y = 3

L = ['4','8','m']

for i in L:
  row_q = [] 
  col_q = []
  pixel_counted = np.zeros((row,col)).astype(bool)
  pixel_paths = []
  steps_in_path = 0
  current_branch_pixel_count = 1
  next_branch_pixels_count = 0
  end_reached = False
  if i == '4':
    path4 = calculate_path('4',A,V2)
  elif i == '8':
    path8 = calculate_path('8',A,V2)
  elif i =='m':
    pathm = calculate_path('m',A,V2)
    
    
    
print("Image1-V2 = \n",A)
print("Set =",V2)
print("Path4 = ",path4)
print("Path8 = ",path8)
print("Pathm = ",pathm)
print('\n')

t_total = time.time()- start_time
print(t_total)

Image1-V1 = 
 [[3 1 2 1]
 [2 2 0 2]
 [1 2 1 1]
 [1 0 1 2]]
Set = [0, 1]
Path4 =  False
Path8 =  (4, [[3, 0], [3, 1], [2, 2], [1, 2], [0, 3]])
Pathm =  (5, [[3, 0], [3, 1], [3, 2], [2, 2], [2, 3], [0, 3]])


Image1-V2 = 
 [[3 1 2 1]
 [2 2 0 2]
 [1 2 1 1]
 [1 0 1 2]]
Set = [1, 2]
Path4 =  (6, [[3, 0], [2, 0], [2, 1], [2, 2], [2, 3], [1, 3], [0, 3]])
Path8 =  (4, [[3, 0], [2, 1], [3, 2], [3, 3], [0, 3]])
Pathm =  (6, [[3, 0], [2, 0], [2, 1], [2, 2], [2, 3], [1, 3], [0, 3]])


0.005321979522705078


In [30]:
# Example 3
A = np.array(([1,0,1,2,3],[3,1,2,1,1],[2,2,0,2,1],[2,2,0,2,1],[1,2,1,1,3]))
row = A.shape[0]
col = A.shape[1] 
V1 = [2,3]
start_pixel_x = 1
start_pixel_y = 2
end_pixel_x = 3
end_pixel_y = 3

L = ['4','8','m']

for i in L:
  row_q = [] 
  col_q = []
  pixel_counted = np.zeros((row,col)).astype(bool)
  pixel_paths = []
  steps_in_path = 0
  current_branch_pixel_count = 1
  next_branch_pixels_count = 0
  end_reached = False
  if i == '4':
    path4 = calculate_path('4',A,V2)
  elif i == '8':
    path8 = calculate_path('8',A,V2)
  elif i =='m':
    pathm = calculate_path('m',A,V2)
    
    
    
print("Image2 = \n",A)
print("Set =",V1)
print("Path4 = ",path4)
print("Path8 = ",path8)
print("Pathm = ",pathm)
print('\n')

Image2 = 
 [[1 0 1 2 3]
 [3 1 2 1 1]
 [2 2 0 2 1]
 [2 2 0 2 1]
 [1 2 1 1 3]]
Set = [2, 3]
Path4 =  (3, [[1, 2], [1, 1], [2, 1], [3, 3]])
Path8 =  (2, [[1, 2], [2, 3], [3, 3]])
Pathm =  (3, [[1, 2], [1, 1], [0, 0], [3, 3]])




In [40]:
# Example 4
A = np.array(([1,0,1,2,3,2],[3,1,2,1,1,0],[2,2,0,2,1,1],[2,2,0,2,1,3],[1,2,1,1,3,0]))
row = A.shape[0]
col = A.shape[1] 
V1 = [1,2]
start_pixel_x = 0
start_pixel_y = 1
end_pixel_x = 2
end_pixel_y = 3

L = ['4','8','m']

for i in L:
  row_q = [] 
  col_q = []
  pixel_counted = np.zeros((row,col)).astype(bool)
  pixel_paths = []
  steps_in_path = 0
  current_branch_pixel_count = 1
  next_branch_pixels_count = 0
  end_reached = False
  if i == '4':
    path4 = calculate_path('4',A,V2)
  elif i == '8':
    path8 = calculate_path('8',A,V2)
  elif i =='m':
    pathm = calculate_path('m',A,V2)
    
    
    
print("Image3 = \n",A)
print("Set =",V1)
print("Path4 = ",path4)
print("Path8 = ",path8)
print("Pathm = ",pathm)
print('\n')

Image3 = 
 [[1 0 1 2 3 2]
 [3 1 2 1 1 0]
 [2 2 0 2 1 1]
 [2 2 0 2 1 3]
 [1 2 1 1 3 0]]
Set = [1, 2]
Path4 =  (4, [[0, 1], [0, 0], [0, 3], [1, 3], [2, 3]])
Path8 =  (2, [[0, 1], [1, 2], [2, 3]])
Pathm =  (4, [[0, 1], [0, 0], [0, 3], [1, 3], [2, 3]])




In [39]:
# Example 5
A = np.array(([1,0,1,2,3,2],[3,1,2,1,1,0],[2,2,0,2,1,1],[2,2,0,2,1,3],[1,2,1,1,3,0],[1,2,0,1,3,2]))
row = A.shape[0]
col = A.shape[1] 
V1 = [2,3]
start_pixel_x = 0
start_pixel_y = 1
end_pixel_x = 3
end_pixel_y = 3

L = ['4','8','m']

for i in L:
  row_q = [] 
  col_q = []
  pixel_counted = np.zeros((row,col)).astype(bool)
  pixel_paths = []
  steps_in_path = 0
  current_branch_pixel_count = 1
  next_branch_pixels_count = 0
  end_reached = False
  if i == '4':
    path4 = calculate_path('4',A,V2)
  elif i == '8':
    path8 = calculate_path('8',A,V2)
  elif i =='m':
    pathm = calculate_path('m',A,V2)
    
    
    
print("Image4 = \n",A)
print("Set =",V1)
print("Path4 = ",path4)
print("Path8 = ",path8)
print("Pathm = ",pathm)
print('\n')

Image4 = 
 [[1 0 1 2 3 2]
 [3 1 2 1 1 0]
 [2 2 0 2 1 1]
 [2 2 0 2 1 3]
 [1 2 1 1 3 0]
 [1 2 0 1 3 2]]
Set = [2, 3]
Path4 =  (5, [[0, 1], [0, 0], [0, 3], [1, 3], [1, 4], [3, 3]])
Path8 =  (3, [[0, 1], [1, 2], [2, 3], [3, 3]])
Pathm =  (5, [[0, 1], [0, 0], [0, 3], [1, 3], [1, 4], [3, 3]])


